### ISSUE TITLE
Better tutorial and documents

### ISSUE THREAD

**Issue by marty1885** [etaler/Etaler#46]
Related to #45.
We definitely need better documents and tutorials for new comers to join easily. How and in what kinds of tutorial and documents do we need?

**Comment by cyberslam** [comment]
Better installation:  just a step-by-step installation guide.  It will be great if it all could be done via 
                               Colab - since we can save the results for future reference under that 
                               environment.

Better examples:  it will be great if we could use the htm.core's 3 examples so as to cross check and
                           to give confident that your new rewrite and it's RESULT did NOT deviate from the 
                           the main group too much.  I really would appreciate to compare the results from
                           "HotGym" example.  (Off-topic: I was disappointed that I was not able to generate
                           plots using htm.core under Colab and especially for the "hotgym" example).

Ultimate example: if you could develop a python front end, using Etaler as back end, and produce a
                           Jupyter Notebook like in "https://github.com/psdyer/NuPIC-Algorithm-API-Example",
                           and PRODUCE THE SAME RESULTS, 
                           then everyone could understand the nupic's inherent concept and modify their own 
                           parameters to suit their needs.
          
   Samuel

**Comment by marty1885** [comment]
@cyberslam Please do post any building problem you met so we can help. And we have published building instructions [here][1], [here][2] and [here][3]. They might not be concrete but should serve as a goo starting point. Though you might want to manuly disable the visualizer example as it is a bit difficult to build on non-Linux systems. (I'm gonna ask alior for that). 

Yeah.. I think making equivalent examples as HTM,core's will be a good idea. And thus be able to verify that our implementation is correct. **note to myself:** Well... Etaler implements an alternative version of TemporalMemory, where there i only my segment per cell and using the conenct-to-all learning method. This solves the repeating input problem. So we might not get the same results.

[1]: https://github.com/etaler/Etaler#building-from-source 
[2]: https://github.com/etaler/Etaler/blob/master/docs/BuildOnMSVC.md
[3]: https://github.com/etaler/Etaler/blob/master/docs/BuildOnOSX.md

**Comment by marty1885** [comment]
As for notebooks. We sure will make notebooks when we have the Python wrapper made. But in the mean while. Why not try a C++ notebook? :)

![image](https://user-images.githubusercontent.com/8792393/62340769-4a799980-b513-11e9-9443-0012ebfe3618.png)

**Comment by marty1885** [comment]
@cyberslam I don't have a Python wrapper yet. But I have built a C++ notebook prototype. You might want to have a look at it.
https://gist.github.com/marty1885/e7f5eacb17a1c328cf0f4ae2ed9ea648

**Comment by cyberslam** [comment]
Thanks Martin.  I will try to run it under the Colab notebook in the early next week.  Too busy this weekend.SamuelSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Martin Chang <notifications@github.com> Date: 2019-08-03  10:01 p.m.  (GMT-08:00) To: etaler/Etaler <Etaler@noreply.github.com> Cc: cyberslam <sflam168@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [etaler/Etaler] Better tutorial and documents (#46) @cyberslam I don't have a Python wrapper yet. But I have built a C++ notebook prototype. You might want to have a look at it.
https://gist.github.com/marty1885/e7f5eacb17a1c328cf0f4ae2ed9ea648

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/etaler/Etaler/issues/46?email_source=notifications\u0026email_token=ACGVJNTO334FIGNRADKUFZDQCZPBJA5CNFSM4IIOD3K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3P2PRI#issuecomment-517973957",
"url": "https://github.com/etaler/Etaler/issues/46?email_source=notifications\u0026email_token=ACGVJNTO334FIGNRADKUFZDQCZPBJA5CNFSM4IIOD3K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3P2PRI#issuecomment-517973957",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by marty1885** [comment]
I don't think you can run the notebook on Colab :(
The notebook depends on ROOT, which is not available on Colab.

**Comment by marty1885** [comment]
Online documents are now available at https://etaler.readthedocs.io/en/latest/

I'll add more as time goes.

Feel free to re-open the issue.
