### ISSUE TITLE
example1 with OpenCL fails on assert

### ISSUE THREAD

**Issue by alior101** [etaler/Etaler#53]
I modified SP to have opencl default backend 

```
Backend* et::defaultBackend()
{
	using DefaultBackendType = OpenCLBackend;
	if(g_default_backend == nullptr) {
		//std::cerr << "Error: defaultBackend() called before setting the default backend.\n";
		//abort();
		if((bool)g_default_backend_hold == false)
			g_default_backend_hold = std::make_shared<DefaultBackendType>();

		g_default_backend = g_default_backend_hold.get();
	}
	return g_default_backend;
}

```
and then modified example1

```
int main()
{
	//std::shared_ptr<Backend> backend = std::make_shared<OpenCLBackend>();
	//setDefaultBackend(backend);

	//Create a SP that takes in 128 input bits and generates 32 bit representation
	auto gpu = std::make_shared<OpenCLBackend>();

	SpatialPooler sp({128}, {32});
	//sp.to(gpu.get());

	//Encode the value 0.1 into a 32 bit SDR
	Tensor x = encoder::scalar(0.1, 0, 1, 128, 12);
	Tensor x1 = x.to(gpu);

	std::cout << sp.compute(x1) << std::endl;

	auto state = sp.states();
	sp.loadState(state);
}

```
running it fails on sp.compute with

`Assertion connections->backend() == this failed`

**Comment by marty1885** [comment]
Ahh... This is the intended behaviour.

In your code
```c++
auto gpu = std::make_shared<OpenCLBackend>();
SpatialPooler sp({128}, {32});
//Encode the value 0.1 into a 32 bit SDR
Tensor x = encoder::scalar(0.1, 0, 1, 128, 12);
Tensor x1 = x.to(gpu);
```

Since you didn't use setDefaultBackend(). SP is initialized on the CPUBackend. But x1 is on OpenCL. So, it crashes. (This is the same behaviour if you add two tensors on different backends on PyTorch)

**Comment by alior101** [comment]
it happens even if I move the sp to gpu with
sp.to(gpu.get());

Maybe I'm doing it wrong ?

**Comment by marty1885** [comment]
> Maybe I'm doing it wrong ?
It is my fault. I didn't read your code closely enough.

You have modified that.
```C++
using DefaultBackendType = OpenCLBackend;
```

So when ever `defaultBackend()` is called and no backend is available, it creates a new OpenCL backend for you.

Then you called `auto gpu = std::make_shared<OpenCLBackend>();` afterwords. Creating a second OpenCL backend. Then the SP is created on the 1st OpenCLBackend, while  `x.to(gpu)` sends x to the 2nd OpenCLBackend.

The objects are living under a different OpeCL Context (think they are on a different server). So it crashes.

---

Since you have modified `defaultBackend()` you give you an OpenCLBackend. You don't need to create one yourself. You can leave the code alone and things should work.


```c++
int main()
{
	//std::shared_ptr<Backend> backend = std::make_shared<OpenCLBackend>();
	//setDefaultBackend(backend);

	//Create a SP that takes in 128 input bits and generates 32 bit representation
	//auto gpu = std::make_shared<OpenCLBackend>();

	SpatialPooler sp({128}, {32});
	//sp.to(gpu.get());

	//Encode the value 0.1 into a 32 bit SDR
	Tensor x = encoder::scalar(0.1, 0, 1, 128, 12);
	Tensor x1 = x.to(gpu);

	std::cout << sp.compute(x1) << std::endl;

	auto state = sp.states();
	sp.loadState(state);
}
```

**Comment by alior101** [comment]
working after merge with master
